### ISSUE TITLE
Be less restrictive on guzzle

### ISSUE THREAD

**Issue by ligams** [nuxeo/nuxeo-php-client#12]
This makes the lib incomptaible too often as of it is not updated really often :

`"guzzlehttp/guzzle": "6.3.*",`

Could be change in

`"guzzlehttp/guzzle": "~6.3",`

in [composer.json](https://github.com/nuxeo/nuxeo-php-client/blob/master/composer.json#L20)

**Comment by pgmillon** [comment]
I understand the pain with being so restrictive but guzzle already broke the API in a minor release (I don't have the ref).
Can you specify which version is pulled by your other dependencies in your project ? 
I'll try to do a dependencies update but I'd like to make sure it fits your needs.

**Comment by pgmillon** [comment]
Meanwhile, I changed the dependencies management to specify a minimum version but keep a restriction on the upper bound limit (should be properly tested before increasing it).
It should let you use the lib with Guzzle up to 6.5.* at the time of this writing.
I'll try to release those changes (available on dev-master) in the next days.
Regards.

**Comment by pgmillon** [comment]
Hi,
I just released 2.1.1 that allows up to the latest 6.6.* of guzzlehttp/guzzle that has been tested and working correctly.
