### ISSUE TITLE
symfony/http-foundation not found

### ISSUE THREAD

**Issue by Ak1r0** [nuxeo/nuxeo-php-client#8]
Hi,

I got this error :

> Class 'Symfony\Component\HttpFoundation\ResponseHeaderBag' not found in .../vendor/nuxeo/nuxeo-automation-php-client/src/Nuxeo/Client/Internals/Spi/Http/Header/ContentDisposition.php on line 44 

I think `symfony/http-foundation` must be __require__ and not __require-dev__ in your composer.json

Cheers,

Matthieu

**Comment by pgmillon** [comment]
Hi,
Sorry for the long delay. This is now fixed with 1.5.1.
I also reviewed the ftest to be able to detect any unwanted require-dev.
Please consider upgrading to 2.0+ as 1.5+ is deprecated.
